CREATE SEQUENCE books_id_seq;
CREATE SEQUENCE authors_id_seq;
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Statistical Snacks');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Metin Bektas');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Making Games with Python & Pygame');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Al Sweigart');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Invent Your Own Computer Games with Python');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Al Sweigart');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Hacking Secret Ciphers with Python');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Al Sweigart');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Automate the Boring Stuff with Python: Practical Programming for Total Beginners');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Al Sweigart');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Python Playground: Geeky Projects for the Curious Programmer');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Mahesh Venkitachalam');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Python Crash Course: A Hands-On, Project-Based Introduction to Programming');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Eric Matthe');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Doing Math with Python: Use Programming to Explore Algebra, Statistics, Calculus, and More!');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Amit Saha');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'The Magic of Math: Solving for x and Figuring Out Why');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Arthur Benjamin');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Better Explained: A Guide To Developing Lasting Intuition');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Kalid Azad');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Math Dialogue: Functions');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Metin Bektas');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Math Concepts Everyone Should Know (And Can Learn');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Metin Bektas');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
INSERT INTO books VALUES ( nextval('books_id_seq'), 'Statistical Snacks');
INSERT INTO authors VALUES ( nextval('authors_id_seq'), 'Metin Bektas');
INSERT INTO association VALUES (currval('books_id_seq'), currval('authors_id_seq'));
